[package]
name = "tpmiddle-rs"
version = "0.1.0"
authors = ["SeongChan Lee"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0.32"
field-offset = "^0.3.2"
aligned = "^0.3.4"
crossbeam-channel = "^0.4.4"

[dependencies.winapi]
version = "^0.3.9"
features = [
    "basetsd",
    "minwindef",
    "ntdef",
    "winbase",
    "winuser",
    "windef",
    "errhandlingapi",
    "libloaderapi",
    "impl-default"
]
